# Generated by Django 3.1.3 on 2020-12-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showid', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('profile', models.ManyToManyField(to='main_app.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieId', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('profile', models.ManyToManyField(to='main_app.Profile')),
            ],
        ),
    ]
