# Generated by Django 3.1.3 on 2020-12-01 23:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_movie_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='show',
            name='profile',
        ),
        migrations.AddField(
            model_name='movie',
            name='User',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='show',
            name='User',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
