# Generated by Django 3.1.3 on 2020-12-07 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_review_review_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='movie_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='show_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
