# Generated by Django 3.1.3 on 2020-12-01 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20201201_2317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='User',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='User',
            new_name='user',
        ),
    ]
