# Generated by Django 3.1.3 on 2020-12-02 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20201201_2319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movieId',
            new_name='movie_id',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='showid',
            new_name='show_id',
        ),
    ]
