# Generated by Django 3.1.3 on 2020-12-09 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20201209_0216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='movie_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='review',
            name='show_title',
        ),
    ]
